# generated by datamodel-codegen:
#   filename:  events.schema.json

from __future__ import annotations

from datetime import date as _date, datetime
from typing import Literal, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class SessionStart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    ts: datetime
    type: Literal['session_start']
    book_id: constr(min_length=1)
    target_seconds: conint(ge=1)


class BlockRead(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    ts: datetime
    type: Literal['block_read']
    block_id: constr(min_length=1)
    seconds: conint(ge=0)


class Answer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    ts: datetime
    type: Literal['answer']
    question_id: constr(min_length=1)
    correct: bool


class Checkin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    ts: datetime
    type: Literal['checkin']
    date: _date = Field(
        ..., description='已按偏移自然日换算好的打卡日，不是 ts 的原始时间戳'
    )


class SettingsChange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    ts: datetime
    type: Literal['settings_change']
    key: constr(min_length=1)
    value: Union[str, float, bool] = Field(
        ..., description='设置值，类型依 key 而定（如 daily_target_seconds 是 integer）'
    )


class Event(RootModel[Union[SessionStart, BlockRead, Answer, Checkin, SettingsChange]]):
    root: Union[SessionStart, BlockRead, Answer, Checkin, SettingsChange] = Field(
        ...,
        description='kuibu 用户状态事件日志（JSONL，每行一个 Event），按 type 区分 5 种事件',
        title='Event',
    )
