# generated by datamodel-codegen:
#   filename:  pack.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Manifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: str = Field(
        ..., description='内容包遵循的 schema 版本，阅读器加载时据此校验'
    )
    book_id: constr(min_length=1)
    title: constr(min_length=1)
    author: str
    license: str
    source: str
    generated_at: datetime
    generator_version: str


class Block(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    seq: conint(ge=1)
    section_path: List[str] = Field(..., min_length=1)
    section_title: constr(min_length=1)
    content_md: str
    est_seconds: conint(ge=1)
    recap_md: str


class KnowledgeItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    block_ids: List[str] = Field(..., min_length=1)
    statement: constr(min_length=1)
    question_ids: List[str] = Field(..., min_length=1)


class Type(Enum):
    single_choice = 'single_choice'


class Question(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    item_id: constr(min_length=1)
    type: Type
    prompt: constr(min_length=1)
    options: List[str] = Field(..., min_length=2)
    answer_index: conint(ge=0)
    explanation: str


class Exercise(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    block_id: constr(min_length=1) = Field(
        ..., description='读完这个 block 之后，这道习题才会出现在当天的可选习题列表里'
    )
    number: constr(min_length=1) = Field(
        ..., description='原书自己的习题编号，如 "1.9"，纯展示用，不参与排序/调度'
    )
    prompt_md: str = Field(
        ...,
        description='习题原文，逐字从原书切出来，不是复述——跟 block.content_md 是同一条铁律',
    )
    hint_md: str = Field(
        ...,
        description='提示（不是答案）。当前阶段刻意不提供答案，只给一个不透题的提示',
    )


class RecapCheckpoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    through_block_count: conint(ge=1) = Field(
        ...,
        description='这条回顾覆盖了累计读到第几个 block（按 seq 计数，不是按天数）——运行时取 <= 用户实际已读 block 数里最大的那一条，不依赖任何每日阅读时长的假设',
    )
    recap_md: str = Field(
        ...,
        description='对累计读过的内容的回顾，构建期一次性写好，阅读器运行时只做查表，不重新生成',
    )


class SectionHeading(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: List[str] = Field(
        ...,
        description='章/节这一级的路径，如 ["1"]（章）或 ["1","1.1"]（节）——不是 block 的完整叶子路径',
        min_length=1,
    )
    title: constr(min_length=1) = Field(
        ..., description='原书自己的章/节标题，机械从原文标题标签里提取，不是生成器编的'
    )


class ContentPack(BaseModel):
    """
    kuibu 内容包：manifest + blocks + items + questions + exercises + recap_checkpoints + section_headings 的组合视图
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    manifest: Manifest
    blocks: List[Block]
    items: List[KnowledgeItem]
    questions: List[Question]
    exercises: List[Exercise]
    recap_checkpoints: List[RecapCheckpoint]
    section_headings: List[SectionHeading]
