# generated by datamodel-codegen:
#   filename:  pack.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Manifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: str = Field(
        ..., description='内容包遵循的 schema 版本，阅读器加载时据此校验'
    )
    book_id: constr(min_length=1)
    title: constr(min_length=1)
    author: str
    license: str
    source: str
    generated_at: datetime
    generator_version: str


class Block(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    seq: conint(ge=1)
    section_path: List[str] = Field(..., min_length=1)
    section_title: constr(min_length=1)
    content_md: str
    est_seconds: conint(ge=1)
    recap_md: str


class KnowledgeItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    block_ids: List[str] = Field(..., min_length=1)
    statement: constr(min_length=1)
    question_ids: List[str] = Field(..., min_length=1)


class Type(Enum):
    single_choice = 'single_choice'


class Question(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    item_id: constr(min_length=1)
    type: Type
    prompt: constr(min_length=1)
    options: List[str] = Field(..., min_length=2)
    answer_index: conint(ge=0)
    explanation: str


class ContentPack(BaseModel):
    """
    kuibu 内容包：manifest + blocks + items + questions 的组合视图
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    manifest: Manifest
    blocks: List[Block]
    items: List[KnowledgeItem]
    questions: List[Question]
