/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * kuibu 用户状态事件日志（JSONL，每行一个 Event），按 type 区分 5 种事件
 */
export type Event = SessionStart | BlockRead | Answer | Checkin | SettingsChange | ExerciseAttempt;

export interface SessionStart {
  id: string;
  ts: string;
  type: "session_start";
  book_id: string;
  target_seconds: number;
}
export interface BlockRead {
  id: string;
  ts: string;
  type: "block_read";
  block_id: string;
  seconds: number;
}
export interface Answer {
  id: string;
  ts: string;
  type: "answer";
  question_id: string;
  correct: boolean;
}
export interface Checkin {
  id: string;
  ts: string;
  type: "checkin";
  /**
   * 已按偏移自然日换算好的打卡日，不是 ts 的原始时间戳
   */
  date: string;
}
export interface SettingsChange {
  id: string;
  ts: string;
  type: "settings_change";
  key: string;
  /**
   * 设置值，类型依 key 而定（如 daily_target_seconds 是 integer）
   */
  value: string | number | boolean;
}
export interface ExerciseAttempt {
  id: string;
  ts: string;
  type: "exercise_attempt";
  exercise_id: string;
  /**
   * 花在这道习题上的时间；计入当天阅读时长反馈，但不参与 block 切分估时
   */
  seconds: number;
  used_hint: boolean;
}
