/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * kuibu 内容包：manifest + blocks + items + questions 的组合视图
 */
export interface ContentPack {
  manifest: Manifest;
  blocks: Block[];
  items: KnowledgeItem[];
  questions: Question[];
}
export interface Manifest {
  /**
   * 内容包遵循的 schema 版本，阅读器加载时据此校验
   */
  schema_version: string;
  book_id: string;
  title: string;
  author: string;
  license: string;
  source: string;
  generated_at: string;
  generator_version: string;
}
export interface Block {
  id: string;
  seq: number;
  /**
   * @minItems 1
   */
  section_path: [string, ...string[]];
  section_title: string;
  content_md: string;
  est_seconds: number;
  recap_md: string;
}
export interface KnowledgeItem {
  id: string;
  /**
   * @minItems 1
   */
  block_ids: [string, ...string[]];
  statement: string;
  /**
   * @minItems 1
   */
  question_ids: [string, ...string[]];
}
export interface Question {
  id: string;
  item_id: string;
  type: "single_choice";
  prompt: string;
  /**
   * @minItems 2
   */
  options: [string, string, ...string[]];
  answer_index: number;
  explanation: string;
}
