/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * kuibu 内容包：manifest + blocks + items + questions + exercises 的组合视图
 */
export interface ContentPack {
  manifest: Manifest;
  blocks: Block[];
  items: KnowledgeItem[];
  questions: Question[];
  exercises: Exercise[];
}
export interface Manifest {
  /**
   * 内容包遵循的 schema 版本，阅读器加载时据此校验
   */
  schema_version: string;
  book_id: string;
  title: string;
  author: string;
  license: string;
  source: string;
  generated_at: string;
  generator_version: string;
}
export interface Block {
  id: string;
  seq: number;
  /**
   * @minItems 1
   */
  section_path: [string, ...string[]];
  section_title: string;
  content_md: string;
  est_seconds: number;
  recap_md: string;
}
export interface KnowledgeItem {
  id: string;
  /**
   * @minItems 1
   */
  block_ids: [string, ...string[]];
  statement: string;
  /**
   * @minItems 1
   */
  question_ids: [string, ...string[]];
}
export interface Question {
  id: string;
  item_id: string;
  type: "single_choice";
  prompt: string;
  /**
   * @minItems 2
   */
  options: [string, string, ...string[]];
  answer_index: number;
  explanation: string;
}
export interface Exercise {
  id: string;
  /**
   * 读完这个 block 之后，这道习题才会出现在当天的可选习题列表里
   */
  block_id: string;
  /**
   * 原书自己的习题编号，如 "1.9"，纯展示用，不参与排序/调度
   */
  number: string;
  /**
   * 习题原文，逐字从原书切出来，不是复述——跟 block.content_md 是同一条铁律
   */
  prompt_md: string;
  /**
   * 提示（不是答案）。当前阶段刻意不提供答案，只给一个不透题的提示
   */
  hint_md: string;
}
