/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * kuibu 内容包：manifest + blocks + items + questions + exercises + recap_checkpoints + section_headings 的组合视图
 */
export interface ContentPack {
  manifest: Manifest;
  blocks: Block[];
  items: KnowledgeItem[];
  questions: Question[];
  exercises: Exercise[];
  recap_checkpoints: RecapCheckpoint[];
  section_headings: SectionHeading[];
}
export interface Manifest {
  /**
   * 内容包遵循的 schema 版本，阅读器加载时据此校验
   */
  schema_version: string;
  book_id: string;
  title: string;
  author: string;
  license: string;
  source: string;
  generated_at: string;
  generator_version: string;
}
export interface Block {
  id: string;
  seq: number;
  /**
   * @minItems 1
   */
  section_path: [string, ...string[]];
  section_title: string;
  content_md: string;
  est_seconds: number;
  recap_md: string;
}
export interface KnowledgeItem {
  id: string;
  /**
   * @minItems 1
   */
  block_ids: [string, ...string[]];
  statement: string;
  /**
   * @minItems 1
   */
  question_ids: [string, ...string[]];
}
export interface Question {
  id: string;
  item_id: string;
  type: "single_choice";
  prompt: string;
  /**
   * @minItems 2
   */
  options: [string, string, ...string[]];
  answer_index: number;
  explanation: string;
}
export interface Exercise {
  id: string;
  /**
   * 读完这个 block 之后，这道习题才会出现在当天的可选习题列表里
   */
  block_id: string;
  /**
   * 原书自己的习题编号，如 "1.9"，纯展示用，不参与排序/调度
   */
  number: string;
  /**
   * 习题原文，逐字从原书切出来，不是复述——跟 block.content_md 是同一条铁律
   */
  prompt_md: string;
  /**
   * 提示（不是答案）。当前阶段刻意不提供答案，只给一个不透题的提示
   */
  hint_md: string;
}
export interface RecapCheckpoint {
  id: string;
  /**
   * 这条回顾覆盖了累计读到第几个 block（按 seq 计数，不是按天数）——运行时取 <= 用户实际已读 block 数里最大的那一条，不依赖任何每日阅读时长的假设
   */
  through_block_count: number;
  /**
   * 对累计读过的内容的回顾，构建期一次性写好，阅读器运行时只做查表，不重新生成
   */
  recap_md: string;
}
export interface SectionHeading {
  /**
   * 章/节这一级的路径，如 ["1"]（章）或 ["1","1.1"]（节）——不是 block 的完整叶子路径
   *
   * @minItems 1
   */
  path: [string, ...string[]];
  /**
   * 原书自己的章/节标题，机械从原文标题标签里提取，不是生成器编的
   */
  title: string;
}
